<script>
	const title = "Why 3PS?"
	const p1 = {
		paragraph: `<p>The entertainment industry has changed drastically in the recent decade. Music has become nearly free on a subscription based system, with music apps where you can play a song thousands of times, with the artist only making pennies.</p><br><p>Due to the COVID-19 pandemic, the industry came to an instant halt and shut everything down. While some artists took advantage of the free time and put all their energy into producing new work, the year 2020 has made many in the arts lose enthusiasm and initiative.</p><br><p>For many, as work came to a screeching halt, they tried to cope with seclusion, anxiety and struggle to stay safe. Almost all of their marketing resources (e.g., bars, lounges, and venues) shut down.</p><br><p>Live music was restricted in public places. Artists of all kinds had to contend with, at best, smaller audiences. 2020 made it almost impossible for an artist to succeed by means of real-life performance or showcase.</p><br><p></p><br><p>Over the last decade, music venues simply did not pay acts like they used to. Those who once played Lincoln Center and The Hollywood bowl have ended up booking cocktail lounges and the local hole in the wall while paying out of their pockets just to fund a tour.</p><br><p>While tour busses and 1st class flights used to be easily factored into a budget, many bands are now booked in coach and renting multiple vans to roll from one gig to the next. Large venues have swamped their calendar with mainstream top 40 on repeat, leaving behind Indie acts and legendary artists alike.</p><br><p>While some audiences prefer the smaller venue experience, the reality is that bands have to multiply those gigs on tour to get close to the payout they once had. Some bands will go months straight on tour with maybe a handful of random days off to breath between gigs and travel.</p><br><p>They may even be lucky enough to receive per diem during the tour, or not. It is definitely a difficult task to be a musician or artist these days. We know that many artist's persist simply for the love of creating “for the people”. 3PS would like to give back as we are part of "the people" these artist's work so hard to please!</p>`,
	}
</script>

<div class="section-container mx-auto px-12">
	<h2 class="text-6xl font-bold mb-8">{title}</h2>
	<p class="h3 mx-auto">{@html p1.paragraph}</p>
</div>

<br />