<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 pass.glb -k -u -s -T
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useSuspense } from '@threlte/extras'

  export const ref = new Group()

  const suspend = useSuspense()

  const gltf = suspend(useGltf('/models/pass.glb', { useDraco: true }))

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Cube" position={[0, 0.25, -0.03]} scale={[0.54, 0.54, 0.0010]}>
      <T.Mesh
        name="Cube001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube001.geometry}
        material={gltf.materials.GLASS}
      />
      <T.Mesh
        name="Cube001_1"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube001_1.geometry}
        material={gltf.materials.pass_atlas}
      />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
