<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 pass.glb -T
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/src/lib/components/pass.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group position={[0, 0.25, -0.03]} scale={[0.54, 0.54, 0.002]}>
      <T.Mesh geometry={gltf.nodes.Cube001.geometry} material={gltf.materials.GLASS} />
      <T.Mesh geometry={gltf.nodes.Cube001_1.geometry} material={gltf.materials.pass_atlas} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
