<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 planetlogo.glb -k -u -s -T
-->

<script>
	import { Group } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf, useGltfAnimations, useSuspense } from '@threlte/extras';

	export const ref = new Group();

	const suspend = useSuspense();

	const gltf = suspend(useGltf('/models/planetlogo-transformed.glb', { useDraco: true }));
	export const { actions, mixer } = useGltfAnimations(gltf, ref);
	$: $actions['spin']?.play();
	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group name="Scene">
			<T.Group name="Sphere">
				<T.Mesh
					name="Sphere_1"
					castShadow
					receiveShadow
					geometry={gltf.nodes.Sphere_1.geometry}
					material={gltf.materials['Material.004']}
				/>
				<T.Mesh
					name="Sphere_2"
					castShadow
					receiveShadow
					geometry={gltf.nodes.Sphere_2.geometry}
					material={gltf.materials['Material.004']}
				/>
				<T.Mesh
					name="Sphere_3"
					castShadow
					receiveShadow
					geometry={gltf.nodes.Sphere_3.geometry}
					material={gltf.materials.Edges}
				/>
			</T.Group>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
