<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 planets-hi.glb -k -r -s -T -D
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'
  
  export const ref = new Group()

  const gltf = useGltf('src/lib/components/planets-hi-transformed.glb', { useDraco: true })
  export const { actions, mixer } = useGltfAnimations(gltf, ref)
  $: $actions['Sun']?.play()
  $: $actions['FirstPlanet']?.play()
  $: $actions['SecondPlanet']?.play()
  $: $actions['ThirdPlanet']?.play()
  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Scene">
      <T.Mesh
        name="Sun"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sun.geometry}
        material={gltf.materials.Sun}
        position={[-0.04, 0.04, -0.1]}
        scale={12.71}
      >
        <T.PointLight
          name="sunL"
          intensity={10.00}
          decay={2}
          color="#e8af32"
          position={[0, 0, 0.01]}
          rotation={[-2.01, 0, -0.44]}
          scale={0.08}
        />
      </T.Mesh>
      <T.Mesh
        name="Moon"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Moon.geometry}
        material={gltf.materials.Mercury}
        position={[-0.04, 0.04, -0.1]}
        scale={2.99}
      />
      <T.Mesh
        name="ThirdPlanet"
        castShadow
        receiveShadow
        geometry={gltf.nodes.ThirdPlanet.geometry}
        material={gltf.materials['3PS']}
        position={[-0.04, 0.04, -0.1]}
        scale={4.61}
      />
      <T.Mesh
        name="Mars"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Mars.geometry}
        material={gltf.materials.Mars}
        position={[-0.04, 0.04, -0.1]}
        scale={2.99}
      />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
