<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 planet.glb -k -u -s -t
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import type { Snippet } from 'svelte'
  import { T, type Props } from '@threlte/core'
  import { useGltf, useGltfAnimations, useSuspense, useDraco } from '@threlte/extras'

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  const suspend = useSuspense()
	const dracoLoader = useDraco()

  ref = new Group()

  type ActionName = 'SphereAction'
  type GLTFResult = {
    nodes: {
      Sphere001: THREE.Mesh
      Sphere001_1: THREE.Mesh
      Sphere001_2: THREE.Mesh
    }
    materials: {
      ['Material.004']: THREE.MeshStandardMaterial
      Face: THREE.MeshStandardMaterial
      Edges: THREE.MeshStandardMaterial
    }
  }

  const gltf = suspend(useGltf<GLTFResult>('/models/planet.glb', { dracoLoader }))

  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)
</script>

<T
  is={ref}
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group name="Scene">
      <T.Group name="WorldOrigin001" />
      <T.Group name="WorldOrigin" />
      <T.Group name="Sphere">
        <T.Mesh
          name="Sphere001"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Sphere001.geometry}
          material={gltf.materials['Material.004']}
        />
        <T.Mesh
          name="Sphere001_1"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Sphere001_1.geometry}
          material={gltf.materials.Face}
        />
        <T.Mesh
          name="Sphere001_2"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Sphere001_2.geometry}
          material={gltf.materials.Edges}
        />
      </T.Group>
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T>
