<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 planets.glb --transform
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('src/lib/components/planets-transformed.glb', { useDraco: true })
  export const { actions,  mixer } = useGltfAnimations(gltf, ref)
  $: $actions['Sun']?.play()
  $: $actions['FirstPlanet']?.play()
  $: $actions['SecondPlanet']?.play()
  $: $actions['ThirdPlanet']?.play()
  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Scene">
      <T.Mesh
        name="Sphere"
        geometry={gltf.nodes.Sphere.geometry}
        material={gltf.materials.solarsystem}
        position={[-0.04, 0.04, -0.1]}
        scale={12.71}
      />
      <T.Mesh
        name="Sphere001"
        geometry={gltf.nodes.Sphere001.geometry}
        material={gltf.materials.solarsystem}
        position={[-0.04, 0.04, -0.1]}
        scale={2.99}
      />
      <T.Mesh
        name="Sphere003"
        geometry={gltf.nodes.Sphere003.geometry}
        material={gltf.materials.solarsystem}
        position={[-0.04, 0.04, -0.1]}
        scale={4.61}
      />
      <T.Mesh
        name="Sphere002"
        geometry={gltf.nodes.Sphere002.geometry}
        material={gltf.materials.solarsystem}
        position={[-0.04, 0.04, -0.1]}
        scale={2.99}
      />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
